### ISSUE TITLE
Error when importing library

### ISSUE THREAD

**Issue by soubenz** [amosjyng/langchain-visualizer#82]
Traceback (most recent call last):
  File "/mnt/g/Other computers/My Computer/ingka/llm/tracing.py", line 1, in <module>
    import langchain_visualizer
  File "/home/alex/miniconda3/envs/py39/lib/python3.9/site-packages/langchain_visualizer/__init__.py", line 8, in <module>
    from .agents.tools import SerpAPIWrapper  # noqa
  File "/home/alex/miniconda3/envs/py39/lib/python3.9/site-packages/langchain_visualizer/agents/tools.py", line 11, in <module>      
    from langchain.utilities.bash import BashProcess
ModuleNotFoundError: No module named 'langchain.utilities.bash'

**Comment by Sparky579** [comment]
I also encountered the same problem.

**Comment by amosjyng** [comment]
Hey sorry, I lost access to my Python development environment, and have yet to set it up again. Are you able to see if it works with langchain v0.0.291?

**Comment by amosjyng** [comment]
Sorry for the wait @soubenz and @Sparky579 . #84 (released with v0.0.32) should make it compatible with the latest langchain now. Let me know if it still doesn't work.
